### PR TITLE
Add "Join Multi-valued cells" to the Functions I episode

### PR DESCRIPTION
**Pull request by cmacdonell**
I've added subheadings for "Splitting" and "Joining"

One thing to consider: the additional splitting done in Exercise 2 may confuse learners as the results of joining "Authors" back together will look different depending on whether they've split "Subjects" in the exercise. Should we presume they've done the exercise?

I'll add some screenshots once we have the episode flow agreed upon.

### CODE REVIEW

**Comment by ostephens** [comment]
Looks good.

If they've done the Challenge, they'd have to undo it for next episode to work, so I think we need to make this clear.

One option would be to move to a single Challenge where they split then join the Subjects - this would avoid a scenario where they try to do one challenge and not the other.

Also suggest we need to include something about choosing a sensible separator. I had an idea that a challenge question could be "Why would you not use a comma as a separator for the Author column"

**Comment by weaverbel** [comment]
I could merge this @cmacdonell but am going to leave it to @ostephens in case he wants to add/amend.

**Comment by cmacdonell** [comment]
@ostephens, I think I like the idea of having the single challenge after both Splitting and Joining have been demonstrated.

I'll also add a discussion of picking a good delimiter.

**Comment by cmacdonell** [comment]
Ok, please let me know what you think of the update.

**Comment by ostephens** [comment]
I like the new material

I think some issues have crept in the ordering etc as you've edited:

* Split/Join exercises still separate - they need joining together
* Exercise 3 appears twice
* Misspelling of separator as 'separaor' in "Choosing a good separator/delimiter" section , 2nd sentence

**Comment by ostephens** [comment]
Looks great - merging!

**Pull request merged**
