### PR TITLE
Lesson updated with new lesson template.

### PR DESCRIPTION
**Pull request by mkuzak**

### CODE REVIEW

**Comment by ccronje** [comment]
Thanks @mkuzak. Can you please confirm you've tested this locally and all is ok? Otherwise I may need to ping @cmacdonell or someone familiar with the new lesson template code to have a look over these changes.

**Comment by mkuzak** [comment]
I tested it locally, also you can see it rendered and try out in my fork
http://mkuzak.github.io/library-openrefine/
I hope I did not miss anything in the migration, with so many files changing it's easy to make a mistake.

**Comment by pitviper6** [comment]
The new template looks nice, but very bullet-y. I wish the exercises were of a slightly different format in some way to make them easily distinguishable, but that's a minor quibble!

**Comment by drjwbaker** [comment]
The exercises are presented very differently at http://data-lessons.github.io/library-shell/02-counting-mining/

**Comment by ostephens** [comment]
I think the issue is that in the OR lesson the 'exercises' are actually things intended to be worked through on screen when you run this as a f2f session. I think in the work @pitviper6 is doing on this would put in some more actual 'exercises' vs the things that are currently headed as 'exercises' in the current lesson

**Comment by pitviper6** [comment]
@ostephens  true dat! I didn't really think about that - that the exercises in the current lessons are worked through in class.  I'll add the exercises using the UCSD dataset with that handy-dandy drop-down template.

I'm FINALLY back from International Data Week and moved into my condo and my shirty cat has stopped growling at the neighbors so I'll be able to get back to working on breaking up the OR basic lesson 1 using the new template w/ the added exercises.

**Comment by mkuzak** [comment]
Yes, so the exercises are supposed to be something that students can solve based on what they just learned. I mentioned it in issue #44

**Pull request merged**
