### PR TITLE
formatting first exercise and adding solution

### PR DESCRIPTION
**Pull request by jt14den**
Formatting the first exercise so it is more task driven and has a hidden solution.

### CODE REVIEW

**Comment by ostephens** [comment]
Thanks @jt14den 

Comments from me:

- Do all tutors use the 'red sticky' approach to indicate problems? Putting this in as a direction in the lesson seems to tie it to a particular teaching approach? Also makes it less like a lesson you can follow on your own
- I wonder if rather than have this 'exercise' hidden we should rather move the current so-called 'exercises' into just the flow of the lesson and add extra challenges/solutions?

Would be good to get some feedback on this approach from others - maybe from one of the other sites that are looking at this lesson in the sprint? 

@cmacdonell would also be good as a reviewer of the approach

**Comment by cmacdonell** [comment]
I'd agree with @ostephens. First, the lesson may not even be attached to a workshop, a learner may be doing it on their own. I'd suggest removing the red sticky comment.

The difficulty I see with the hidden solution is the learners have not seen how to import before. I would see steps like "locate the downloaded file" as fairly critical and hard to know unless they've done work like this before.

I might suggest an add-on exercise where they have to find another CSV and practice importing it.

**Comment by ostephens** [comment]
I had another thought - there are some aspects of the exercise that the user might be expected to work out for themselves - thinking in particular of making sure dates/numbers are not auto converted - this is an option on the screen the user has to find and make sure it isn't checked. This could make a challenge within the larger task/activity of importing a file

**Comment by jt14den** [comment]
Thanks guys, I forgot I had the red sticky note lingo in there. I can change the language. As far as not showing them how to do it before the exercise, that was by design -- coming from the perspective of quiz before lecturing perspective. This has been show to activate prior knowledge -- even if they don't know how to yet -- and students retain more later.  So in this case, they will learn more by looking for the requirements to satisfy on the exercise. I think the problem with it here is that it isn't explicitly reinforced in the lesson afterwards, which you need to do in this model.  Let me rethink this.

**Comment by ccronje** [comment]
Agree with @cmacdonell and @ostephens. @jt14den in the spirit of 'leave no learner behind' (you had a big impact on me in Portland! 😄 ) I'd be worried about challenging a novice so early. I feel at this point it's more important to explain the environment, the options, and help them feel safe/ready to move on with the DOAJ csv. I gave a workshop a few days ago where a few of the learners were overwhelmed with all the encoding options that appear when you enter UTF-8. Thank goodness I didn't have to explain it all because I was overwhelmed as well.

Perhaps the challenges discussed here could be explored in the Advanced OpenRefine lesson?

**Comment by jt14den** [comment]
I like the way exercise 1 now looks, so can remove this PR.  I think the quiz first method is also a topic for the work going on in the instructor training lesson development before dropping in another lesson -- sorry to jump the queue on that.  Thanks for the feedback @ccronje @ostephens @cmacdonell

**Comment by jt14den** [comment]
I'm closing this pull request. Thanks for the feedback!

**Pull request closed without merging**
