### PR TITLE
Changed recommended version to 2.7R C2, replaced references to 2.6

### PR DESCRIPTION
**Pull request by remerjohnson**
Attemped fix for #108 

Please review. Thanks!

### CODE REVIEW

**Comment by cmacdonell** [comment]
Should we get rid of mentioning GoogleRefine 2.5 at this point?

**Comment by remerjohnson** [comment]
That's a good question. afaik 2.5 is still considered a stable release, but in practice it has more bugs than 2.6. It's not clear cut because 2.6 was such a comparatively small release, and 2.5 is still listed as the stable alternative to 2.7RC on the [Refine GitHub](https://github.com/OpenRefine/OpenRefine).  

If we have consensus on dropping 2.5, though, we could do that.

**Comment by cmacdonell** [comment]
@ostephens @ccronje what do you think about dropping GoogleRefine? @drjwbaker @weaverbel comments welcome as well.

**Comment by ostephens** [comment]
Google Refine 2.5 is still the only official "release" (all others are RCs or Beta). While I would recommend 2.7rc2 to anyone, sometimes people have a problem using non-release s/w versions. That's really the only reason for keeping Google Refine in here IMO.

**Comment by cmacdonell** [comment]
I believe the OR community will never release a "stable" version. I'm not sure if this is principle of theirs but it seems so. They went from 2.6rc2 to 2.7rc1 (and now 2.7rc2) without ever releasing a 2.6 stable.

**Comment by ostephens** [comment]
You maybe write :S The move to 2.7rc1/rc2 was a positive sign at the start of this year. I believe we can get to a stable release - but it does seem a struggle.

**Comment by cmacdonell** [comment]
Perhaps we should clearly "recommend" 2.7rc2 and put it first in the list ahead of GR 2.5?

**Comment by ostephens** [comment]
How about something along the lines:

This lesson has been tested with all versions of OpenRefine from 2.5 to 2.7rc2.
OpenRefine 2.7rc2 is recommended

**Comment by cmacdonell** [comment]
👍

**Comment by remerjohnson** [comment]
Added in @ostephens suggestion. Think it looks good now

**Pull request merged**
