### PR TITLE
Use new syntax used in templates to render exercises

### LINKED ISSUE #41: numbering of exercises
Currently exercises are numbered across whole lesson. For example exercises 1 in episode 1 and then 2, 3, 4 in episode 2. I find it more intuitive and easier to maintain when the numbering is per episode. I was wondering what other people think about it.

### PR DESCRIPTION
**Pull request by mkuzak**
Fix #41

### CODE REVIEW

**Comment by ccronje** [comment]
Thanks @mkuzak, it looks like #40 PR edits have come undone in this PR (see file 02 lines 26, 42, file 03 line 132 etc).

**Comment by ccronje** [comment]
We need to make @pitviper6 aware of these changes as she is in the process of rearranging the structure of episodes and adding more examples. I'll await her response before merging. @ostephens and @drjwbaker may be interested as well. All please see discussions #41 & #44.

**Comment by mkuzak** [comment]
@ccronje you're right, sorry. Hold on, I'll fix it.

**Comment by ccronje** [comment]
@mkuzak just checking - did you close this because you would prefer to wait and see @pitviper6's changes first? The SC syntax you started adding (ref #41 & #44) is a good idea too.

**Comment by mkuzak** [comment]
I still want to do this, it's just my forked version got a bit mangled, hence reverted typo corrections. I want to keep commit history clean so I will redo this pull request. There are actually two things I want to change:
- changing to SC style and dropping the numbering
- making the exercises which are actually walk-throughts into parts of the lesson
I'm not sure if @pitviper6 changes will cause any conflicts, but I guess we'll have to see and resolve them.

**Comment by pitviper6** [comment]
First of all, thanks for working on this!  Secondly, I'm in the middle of breaking up the basic lessons I, but we're going a different route than I suggested so I'm going to have to redo my work anyway.  So if you want to go ahead with what you were doing, go for it!  

I'm at International Data Week through Saturday, and then I'm moving on the Monday after, so I won't be able to sit down with it again for at least a week and half!

**Comment by pitviper6** [comment]
Actually, I think I'll go ahead and delete the pull requests altogether!

**Comment by mkuzak** [comment]
I should be done with my changes this week.

**Comment by mkuzak** [comment]
Comparing library-openrefine with swcarpentry/lesson-example shows that we have quite outdated template. We started using it during mozsprint and since then swc lessons have been migrated and a lot of changes to the templates have been made. This might be the reason why the setup does not show up in the menu. Its a guess.

**Comment by pitviper6** [comment]
Since we're breaking up the large lessons into smaller bits, it would definitely be a good time to include switching them to the new template!

**Pull request closed without merging**
