### PR TITLE
Merging recent changes to styles

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by drjwbaker** [comment]
@gvwilson Are the conflicts here worth pausing over?

**Comment by weaverbel** [comment]
This kind of merge too rich for my blood @drjwbaker @gvwilson - leaving it to more experienced hands ... Greg, if I have given you the right rights, you should be able to sort this yourself and thanks a lot too.

**Comment by gvwilson** [comment]
I'll give it a look later this week - thanks.

**Comment by gvwilson** [comment]
Conflict resolved - I think this is safe to merge now. cc @weaverbel @drjwbaker

**Pull request merged**
