### PR TITLE
Updated FIXME headers

### PR DESCRIPTION
**Pull request by ccronje**
Thanks to http://labs.timtom.ch/library-openrefine/

### CODE REVIEW

**Comment by drjwbaker** [comment]
@ccronje okay, now I'm not sure merging this was the right idea.. We now have duplication at http://data-lessons.github.io/library-openrefine/ which is confusing. Am I right in thinking that there are two lesson strands going on here?

**Comment by ccronje** [comment]
@drjwbaker all good, yes there are currently two lesson strands piggy backing here - one for library and one for digital humanities. The aim is to create a new dh-openrefine repo and then clean up each strand.

**Comment by drjwbaker** [comment]
@ccronje Okay. Just checking. As it stands the timings are out, for example, and I just want to make sure that anyone with upcoming events doesn't get caught out by the 'between two things' state the lesson is currently in.

**Comment by ccronje** [comment]
@drjwbaker it is confusing - @weaverbel gave the go ahead to create a dh-openrefine repo to separate the content. Hoping someone can lend a hand to do this, I'll ask on gitter.

**Pull request merged**
