### PR TITLE
adding 02-importing-data formating of exercise and text

### PR DESCRIPTION
**Pull request by jt14den**
@pitviper6 and @ostephens: I'm teaching this material next week in Pittsburgh and am preparing, but thought I'd take the opportunity to wrap the exercises and callouts in the [SWC style template blockquotes](https://swcarpentry.github.io/lesson-example/04-formatting/#special-blockquotes). Let me know if this is not what you want, otherwise I can do it for each episode and send you PRs. You can see what it looks rendered here: http://www.tim-dennis.com/library-openrefine/02-importing-data/

### CODE REVIEW

**Comment by pitviper6** [comment]
I've done all the blockquotes and formatting, I'm just not sure what, if anything, else I need within the repo itself to make it render correctly?  Or does it not need anything as long as I have my formatting correct?  I've just set up jekyll on my machine, so I'm planning on trying to set it up so I can see if I've rendered correctly according to the directions in the SWC lesson example.

**Comment by pitviper6** [comment]
Oh man, I should NOT write comments when I'm in an airport. Yes, @jt14den, I for one would LOVE to have the lessons done in the SWC blockquotes! @ostephens is this OK with you? If it is I'll go ahead and do the merge.

**Comment by ostephens** [comment]
Hi both

I'm good with the block quotes being applied generally,  but I think there is a question as to whether the 'Exercises' in this lesson are 'challenges' in the SWC sense. See #44 

I think we need to leave the exercises as visible (rather than hidden as a 'challenge' callout) - probably we can remove the 'Exercise' header, as these are intended as part of the teaching rather than as challenges. I know there is some desire to work on the lesson more broadly as part of the upcoming Mozilla Sprint - I wonder if sorting out teaching vs challenge material might fit into that?

What do you think?

**Comment by ccronje** [comment]
Hi @jt14den @pitviper6 @ostephens, I had another look through the formatting guide http://swcarpentry.github.io/lesson-example/04-formatting/ and it doesn't look as though there are differences between an exercise and challenge except that the challenge will likely have a drop-down solution eyeball (as opposed to a straight walk through). I think they're both meant to go in the orange box with the pencil icon.

Here's an example of an exercise http://swcarpentry.github.io/instructor-training/11-load/ (Create a faded example...) - and here's one that looks challenge-y http://swcarpentry.github.io/shell-novice/03-create/ (Renaming files).

**Comment by jt14den** [comment]
@ccronje Thanks! I didn't notice that the challenges are now exposed and not hidden. Looking in the styles repo for SWC, I see this was a recent change to make challenges and discussions visible:  https://github.com/swcarpentry/styles/commit/6f6cba4dfd9457e8e81a838f485b869dff2b242d

@pitviper6 @ostephens @drjwbaker @weaverbel do we have a process for keeping in synch with the SWC upstream styles? We should make this happen b/c I def. prefer them visible.

**Comment by weaverbel** [comment]
Is this PR ready to merge?

**Comment by ccronje** [comment]
I don't think so @weaverbel - I think @jt14den wants to implement the latest formatting style (all exercises visible).

**Comment by jt14den** [comment]
@ccronje @weaverbel @pitviper6 @ostephens  I've merged the changes from https://github.com/swcarpentry/styles to the `library-shell` lesson here: 

http://www.tim-dennis.com/library-shell/

You'll see the exercises are visible on the episodes. I haven't looked in the nooks and crannies of the of the lessons, but I like the changes a lot (including the 'improve this page' addition to the navigation). I can work on a PR for OF if you are ok with it.

**Comment by pitviper6** [comment]
Love it! Thanks so much for doing thisand yeah, I'd be all for an OR PR!


Sent from my Sprint Samsung Galaxy S7.
-------- Original message --------From: Tim Dennis <notifications@github.com> Date: 5/13/17  3:58 PM  (GMT-05:00) To: data-lessons/library-openrefine <library-openrefine@noreply.github.com> Cc: Juliane Schneider <juliane.schneider@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [data-lessons/library-openrefine] adding 02-importing-data
  formating of exercise and text (#58) 
@ccronje @weaverbel @pitviper6 @ostephens  I've merged the changes from https://github.com/swcarpentry/styles to the library-shell lesson here:
http://www.tim-dennis.com/library-shell/
You'll see the exercises are visible on the episodes. I haven't looked in the nooks and crannies of the of the lessons, but I like the changes a lot (including the 'improve this page' addition to the navigation). I can work on a PR for OF if you are ok with it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/data-lessons/library-openrefine","title":"data-lessons/library-openrefine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/data-lessons/library-openrefine"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jt14den in #58: @ccronje @weaverbel @pitviper6 @ostephens  I've merged the changes from https://github.com/swcarpentry/styles to the `library-shell` lesson here: \r\n\r\nhttp://www.tim-dennis.com/library-shell/\r\n\r\nYou'll see the exercises are visible on the episodes. I haven't looked in the nooks and crannies of the of the lessons, but I like the changes a lot (including the 'improve this page' addition to the navigation). I can work on a PR for OF if you are ok with it. "}],"action":{"name":"View Pull Request","url":"https://github.com/data-lessons/library-openrefine/pull/58#issuecomment-301271251"}}}

**Comment by ccronje** [comment]
@jt14den thanks! Looks awesome with the new exercise boxes 👍  I didn't look in the nooks and crannies but noticed a few glitches on the home page:

- Missing logo top left
- About page has old logo
- In Episodes menu - All in one page (Beta) isn't working
- Search box doesn't return results

Great that Setup is more prominent on the homepage Schedule.

**Pull request merged**
