### PR TITLE
Added new basic function module working with columns

### PR DESCRIPTION
**Pull request by pitviper6**
This is the first of four new lessons that I'm breaking out of the current "basic functions I" lesson.  What I did was to use a new dataset for the demo (UCSD_Guardian.csv) and then created a new exercise for working with columns using the doaj dataset. I'm going to NOT accept the pull request so that the other maintainers can take a look and see if they like the new approach.  I'll be using the Guardian dataset throughout the demos, and creating new exercises with the doaj dataset so that students can really dig into some hands on exploration of OpenRefine.

### CODE REVIEW

**Comment by ostephens** [comment]
I'm not 100% sure of this approach of having demonstrations using one data set and one for the exercises.

Can we separate the change to the structure of the episodes from the more substantial changes to the way the lesson is delivered and the data used? I think the latter needs some more discussion and agreement from a wider set of people.

**Comment by ccronje** [comment]
Thanks @pitviper6 the structural changes are looking great. I've only worked through the OR module twice but I tend to agree with @ostephens. I think it may be good for beginners to learn and practice with the same dataset (to avoid too many new things to become familiar with). For me the data acts like a reference point, providing bearings while exploring the tool's functionality. Having said that, a bonus/challenge exercise with a second dataset might be a good way to stretch people?

**Comment by drjwbaker** [comment]
Chipping in, I agree - where possible - the keeping the same dataset is best: it does ensure that the dataset doesn't have to be learnt as well as the new skills. So I'd suggest that if it is intended to be part of the 'standard' module I'd recommend revision, but if it is intended as an 'extra' exercise it can use a different data set.

**Comment by pitviper6** [comment]
OK. The reason I mocked this one up is that the feedback for the OR section of our workshop was excellent, with the one caveat that they wanted more hands-on time and that there was too much demo (waiting for those who were slower to catch on was frustrating the fast learners).  SWC instructor training emphasized this as well, that demos and live coding can be pretty exhausting without breaks and an opportunity to apply what they've learned quickly afterwards to reinforce the learning.  I thought using a different dataset would be a good way to have the learners step back and think about how what they just learned would apply to something new, instead of simply parroting the steps that we just went through, encouraging them to work through the exercises in groups to encourage collaborative learning. That's why I added the last question of the exercise - what are the reasons sorting on columns can be useful.

But, what I can do is continue to break apart the existing Basic I lesson into the four separate modules, and then add extra exercises using the UCSDGuarding dataset.

**Comment by ccronje** [comment]
@pitviper6 that sounds like a good way forward - @ostephens, @drjwbaker, @weaverbel what do you think? (for others interested in this conversation please see [Juliane's blog post](http://software-carpentry.org/blog/2016/08/lc-at-ucsd.html))

**Comment by ostephens** [comment]
+1

**Comment by drjwbaker** [comment]
Pedagogical logic makes sense. Go for it!

**Comment by pitviper6** [comment]
OK!  I'll remove this pull request and redo the second dataset as an additional exercise.

**Pull request closed without merging**
