### PR TITLE
Ep04 adding checklist facet

### PR DESCRIPTION
**Pull request by jt14den**
Adding the checklist example from http://www.tim-dennis.com/libcarp-pitt-notes-exercises/03-basic-functions-I/ to `04-faceting-and-filtering.md`.

### CODE REVIEW

**Comment by ccronje** [comment]
Thanks @jt14den 👍 

@jt14den @ostephens 
Do you have any thoughts about when to use backticks? They're used in the description, checklist and exercises at the moment, which I think helps with reading. Also, should the case of backtick text be identical to OpenRefine?

**Comment by ostephens** [comment]
@ccronje not sure I know what you mean - using backticks how? Is there an example?

**Comment by ccronje** [comment]
@ostephens bit cryptic sorry - I meant the things that are rendering blue text on grey background e.g. `Facet > Text Facet`
`include`
`exclude`

**Comment by jt14den** [comment]
Sorry, I have a bit of a markdown markup fetish. I like using the tics to draw attention to inline code or in this case UI steps.  I think I got it from the data carpentry open refine lesson: http://www.datacarpentry.org/OpenRefine-ecology-lesson/02-filter-exclude-sort/

**Comment by ostephens** [comment]
So I'd usually use back ticks/tics for code only (including GREL expressions), but I'm also fine on using it to show OpenRefine menu terms.

I think that we should treat everything inside back ticks as literal - so to answer @ccronje question - Yes I think everything inside the back tick should be the same as OpenRefine text - or in the case of GREL, valid working GREL

**Comment by ccronje** [comment]
Sounds good and nice example from DC - thanks!

**Pull request merged**
