### PR TITLE
Update 37  > 1. Click on the drop down menu

### PR DESCRIPTION
**Pull request by stapleto**
Add an example column to facet for the exercise, e.g Language column.
example:
Update 37  > 1. Click on the drop down menu at the top of the Language column.......
Cheers,
Sharron Stapleton

### CODE REVIEW

**Comment by drjwbaker** [comment]
Thanks Sharron, I'll leave this for the maintainers to look at. @ostephens @ccronje @Juliane666: I noticed when running through the lesson for teaching it this week that there are a number of places where this happens (there is an example workflow but no column to demo as an example). I didn't know whether this was conscious, but I planned to raise an issue and/or PR post-workshop covering all the changes I suggest and discussion points.

**Comment by ccronje** [comment]
Thanks @stapleto. @drjwbaker this is the same as https://github.com/data-lessons/library-openrefine/pull/165. Happy to merge this one if @ostephens is.

**Comment by ostephens** [comment]
Hi all,

I've ended up merging #165 in place of this one - this was on the basis that I think that the Publisher col makes a better example for a first Facet than language (although obviously it doesn't really matter which you use the functionality is the same)

**Comment by ccronje** [comment]
Thanks @ostephens

**Pull request closed without merging**
