### PR TITLE
delete part of sentence that doesn't apply

### PR DESCRIPTION
**Pull request by scottcpeterson**
The last clause in this sentence is missing a couple words, so it doesn't make sense. I also think this part of the sentence might be trying to say something about custom text facets, which are not referred to below. If this is the case, I am not sure this line about custom text facets is necessary.

### CODE REVIEW

**Comment by drjwbaker** [comment]
The bits on bullets here ('Word facet' et al) are all listed as 'Customized Facets'. They are, in effect, common 'Custom facets'. I presume in the lesson it decided to group these under the heading 'Custom facets', because they are suggestive examples of the sort of bespoke facets a user can write?

**Comment by scottcpeterson** [comment]
I think the reason I thought the deleted sentence was a reference to custom text facets is because that sentence seemed to be trying to say something about the users ability to write customized facets, which is what the customized text facet option does in that you can use GREL and Python to write your own facets.

**Comment by ostephens** [comment]
The language in the interface isn't clear here, and my explanation in the text isn't the best. Essentially I'd regard everything below the line separator in the 'Facets' sub-menu to be some type of custom facet - just that some have been written for you already as a shortcut (under the 'Customised facets' sub-menu).

My original wording was clumsy, and happy to see this changed, but I think noting that you can write your own custom text facets is important - I think it is one of the most useful, but slightly hidden, features in OR, and one I use a lot.

I think there needs to be something in this section to indicate you can write your own custom text facets.

**Comment by drjwbaker** [comment]
I agree with @owen that 'I think there needs to be something in this section to indicate you can write your own custom text facets'. Can you point here to Part 7 (Transformations) where the language used to make custom facets (GREL) is explored in more detail?

**Pull request merged**
