### PR TITLE
Split episodes

### PR DESCRIPTION
**Pull request by ostephens**
Proposal for breaking down the 'Basic Functions' episode into smaller chunks. This PR is currently about the structure - so haven't completed the learning objectives etc at the moment

### CODE REVIEW

**Comment by cmacdonell** [comment]
The header titles on episodes IV and V are not correct. They say episode III and II, respectively.

**Comment by ostephens** [comment]
@cmacdonell thanks. Would appreciate feedback on whether you think the restructuring works?

**Comment by cmacdonell** [comment]
I think it's a good idea, but I've only looked at the github diffs. I'll pull a local copy and go through them.

**Comment by cmacdonell** [comment]
@ostephens Yes, I think the splitting is advantageous. Some of the lessons are now too short, like "Functions I", but I think it will help the episodes be more focused as we flesh them out.

If we merge this, we'll really need to push on these new episodes in the next day or so, otherwise the lesson will be hard to teach with the new episodes.  We don't want to leave the repo in that state.

I'm 👍 for merging, but I'd appreciate another set of eyes - @weaverbel, @drjwbaker?

**Comment by ostephens** [comment]
@cmacdonell thanks - would be good to merge sooner than later due to the other work going on round OpenRefine - better to build on this structure if we are happy with it.

@ccronje and/or @pitviper6 would be ideal as another pair of eyes as they are the other maintainers - but may depend when they are around

**Comment by jt14den** [comment]
@ostephens i say thumbs up and if you agree to get it merged sooner than later so we can take full advantage of the sprint.

**Comment by ostephens** [comment]
@cmacdonell are you happy to do the honours?

**Comment by ccronje** [comment]
Clustering appears twice - in http://data-lessons.github.io/library-openrefine/04-basic-functions-II/ and http://data-lessons.github.io/library-openrefine/05-basic-functions-III/

**Pull request merged**
